package metadata

import (
	"encoding/json"
	"github.com/saladtechnologies/salad-cloud-imds-sdk-go/internal/utils"
)

// An API error. The `code` and `type` uniquely identify the type of the error. The `code` is a short value that may be used for programmatic error handling. The `type` is an absolute URL that may be resolved for more detailed information. Refer to the [SaladCloud IMDS reference](https://leaf.salad.com/l/saladcloud-imds-errors) for a list of the expected `code` and `type` values. Also, note that all properties are optional. Clients should implement robust error handling to account for unexpected errors.
type SaladCloudImdsError struct {
	// The error code that identifies the error type. This is a short value that may be used for programmatic error handling.
	Code *string `json:"code,omitempty" maxLength:"100" minLength:"1"`
	// The human-readable explanation specific to this occurrence of the error.
	Detail *string `json:"detail,omitempty" maxLength:"10000" minLength:"1"`
	// The contextualized map of human-readable explanations specific to this occurrence of the error. This is often used to provide property-specific errors, such as validation errors. In these scenarios, the key is the property name and the value is an array of human-readable explanations specific to this property and this occurrence of the error.
	Errors map[string][]string `json:"errors,omitempty"`
	// The URI reference that identifies the specific occurrence of the error.
	Instance *string `json:"instance,omitempty" maxLength:"2048" minLength:"1"`
	// The HTTP status code generated by the origin server for this occurrence of the error.
	Status *int64 `json:"status,omitempty" min:"100" max:"599"`
	// The short, human-readable summary of the error type.
	Title *string `json:"title,omitempty" maxLength:"10000" minLength:"1"`
	// The URI reference that identifies the error type.
	Type_ *string `json:"type,omitempty" maxLength:"2048" minLength:"1"`
}

func (s *SaladCloudImdsError) GetCode() *string {
	if s == nil {
		return nil
	}
	return s.Code
}

func (s *SaladCloudImdsError) SetCode(code string) {
	s.Code = &code
}

func (s *SaladCloudImdsError) GetDetail() *string {
	if s == nil {
		return nil
	}
	return s.Detail
}

func (s *SaladCloudImdsError) SetDetail(detail string) {
	s.Detail = &detail
}

func (s *SaladCloudImdsError) GetErrors() map[string][]string {
	if s == nil {
		return nil
	}
	return s.Errors
}

func (s *SaladCloudImdsError) SetErrors(errors map[string][]string) {
	s.Errors = utils.CloneMap(errors)
}

func (s *SaladCloudImdsError) GetInstance() *string {
	if s == nil {
		return nil
	}
	return s.Instance
}

func (s *SaladCloudImdsError) SetInstance(instance string) {
	s.Instance = &instance
}

func (s *SaladCloudImdsError) GetStatus() *int64 {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SaladCloudImdsError) SetStatus(status int64) {
	s.Status = &status
}

func (s *SaladCloudImdsError) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *SaladCloudImdsError) SetTitle(title string) {
	s.Title = &title
}

func (s *SaladCloudImdsError) GetType_() *string {
	if s == nil {
		return nil
	}
	return s.Type_
}

func (s *SaladCloudImdsError) SetType_(type_ string) {
	s.Type_ = &type_
}

func (s SaladCloudImdsError) String() string {
	jsonData, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return "error converting struct: SaladCloudImdsError to string"
	}
	return string(jsonData)
}
